### ISSUE TITLE
Re-run tests without coverage only after verifying the first error

### ISSUE THREAD

**Issue by mdwhatcott** [smartystreets/goconvey#188]
See the last comments from #178.

**Comment by dsmontoya** [comment]
I have the same issue that in #178 after got a panic during execution. Before that, it was working just perfect. This is the first time I use goconvey, so don't know if I'm missing something. My OS is Mac OS X.
![captura de pantalla 2016-04-12 15 08 17](https://cloud.githubusercontent.com/assets/4193583/14474010/763b07da-00c0-11e6-8d74-fcdd610339c3.png)

**Comment by dsmontoya** [comment]
Suddenly, goconvey worked again but stoped working after I fixed all the compilation errors produced by the join of some files I use for testing purposes. The last output was the following:

`2016/04/13 10:34:17 integration.go:122: File system state modified, publishing current folders... 26287432026 26287432045`

After that message, I didn't receive any kind of feedback, so decided to kill goconvey. After run it again, I got the previous "No data received" issue.

So if I revert the changes and allow the same compilation errors, goconvey works again after a few minutes (not immediately), but stops working again if the build doesn't fail. I mean, I receive all the needed feedback in order to successfully build the files.
