### ISSUE TITLE
Any plans on implementing ShouldFatal?

### ISSUE THREAD

**Issue by bfitzsimmons** [smartystreets/goconvey#305]
Do you have any plans on implementing this complement to ShouldPanic?  The name may be awkward, but the functionality is really the important part.

**Comment by mdwhatcott** [comment]
@bfitzsimmons - Hmm, I'm not sure what that function would do. `ShouldPanic` receives and executes a function within a deferred `recover` call and marks the assertion as failed if no panic happens. What exactly are you proposing for `ShouldFatal`?

**Comment by bfitzsimmons** [comment]
Hmmm...

Perhaps I'm "holding it wrong".  When I attempted to create tests that covered log.Fatal() goconvey didn't seem to be able to catch it.  

Here's the function being tested:
```go
// SetGOMAXPROCS gets the GOMAXPROCS environment variable and sets the config. property of the same name.
func (config *Configuration) SetGOMAXPROCS() {
	var err error

	if os.Getenv("TERRA_GOMAXPROCS") != "" {
		Config.GOMAXPROCS, err = strconv.Atoi(os.Getenv("TERRA_GOMAXPROCS"))
		if err != nil {
			log.Fatal(err)
		}
	}
}
```

Here's the test:
```go
func TestSetGOMAXPROCS(t *testing.T) {
	config := Configuration{}

	Convey("Attempt to retrieve TERRA_GOMAXPROCS from the environment", t, func() {
		Convey("when it doesn't exist", func() {
			os.Setenv("TERRA_GOMAXPROCS", "")

			So(config.SetGOMAXPROCS, ShouldNotPanic)
		})

		Convey("when it does exist, but has an invalid value", func() {
			os.Setenv("TERRA_GOMAXPROCS", "dog")

			So(config.SetGOMAXPROCS, ShouldPanic)
		})

		Convey("when it does exist, *and* has a valid value", func() {
			os.Setenv("TERRA_GOMAXPROCS", "8")

			So(config.SetGOMAXPROCS, ShouldNotPanic)
		})
	})
}
```

Here's the error in the web UI:

![Goconvey error](https://www.evernote.com/shard/s11/sh/99d3d189-567e-4fc0-80ab-93437ad0689a/bb835aaa14585ad55b6ddbfc883b5510/res/190d977f-5c81-4ce5-a896-de9c7c753ac3/skitch.png)

When I change the code to the following I get a Pass (note the change from `log.Fatal()` to `log.Panic()`:
```go
// SetGOMAXPROCS gets the GOMAXPROCS environment variable and sets the config. property of the same name.
func (config *Configuration) SetGOMAXPROCS() {
	var err error

	if os.Getenv("TERRA_GOMAXPROCS") != "" {
		Config.GOMAXPROCS, err = strconv.Atoi(os.Getenv("TERRA_GOMAXPROCS"))
		if err != nil {
			log.Panic(err)
		}
	}
}
```

Success:

![Goconvey pass](https://www.evernote.com/shard/s11/sh/e017247e-6f61-49cb-941f-5f7e8befed17/e68a2ceacdfa911b09cfd9a747724b18/res/e15222c6-14bc-4861-8e3f-3bf7e2651753/skitch.png)

Perhaps it's an issue with using it with the logging lib. I'm using: http://github.com/Sirupsen/logrus?

**Comment by mdwhatcott** [comment]
If your logging library is like the built-in logging package then calling `log.Fatal` invokes `os.Exit(1)`. This is something that the convey package can't catch because the very process that is running the convey library (which invokes the code under test) is being killed prematurely by that log statement. Using log.Panic would actually be a more correct way to integrate with goconvey in this case.

But if we step back a bit to examine the situation, maybe you could have `config.SetGOMAXPROCS()` just return an error which you can check with tests. Then, something at a higher level (outside of the scope of these unit tests) can call `log.Fatal` (and exit the program). Or if that doesn't seem appropriate, you could use an integration-style test that runs the program under test in a sub-shell and then checks for return codes and the contents of `stderr` in this kind of situation.

Unless I misunderstand I don't think the convey package can catch `os.Exit()`, which makes `ShouldBeFatal` (or something like it) impossible.

**Comment by bfitzsimmons** [comment]
> But if we step back a bit to examine the situation, maybe you could have config.SetGOMAXPROCS() just return an error which you can check with tests. Then, something at a higher level (outside of the scope of these unit tests) can call log.Fatal (and exit the program).

That is exactly what I did immediately after posting my last response.  It's working out better overall.

Thank you for taking the time to write such a thoughtful and thorough response.  I'm loving the app, and it has changed the way I develop.  I'm far more cognizant of keeping test coverage high and accurate, and I think I'm writing better code as a result.

Thanks again, and keep up the good work!
