### ISSUE TITLE
Split filesystem watcher into separate module

### ISSUE THREAD

**Issue by ianwalter** [smartystreets/goconvey#334]
goconvey's file watcher seems to be the only system that works in Docker (Docker Machine). I'm simply trying to build my application and re-run it when a file changes, but most of the tools that try to do this haven't worked for me (gin, fresh). goconvey seems to work fine and re-runs my tests on file change. So I was just wondering if someone would be open to splitting it out?

**Comment by fzerorubigd** [comment]
I use this one https://github.com/codeskyblue/fswatch and every thing is fine inside docker.

**Comment by mdwhatcott** [comment]
The file watching mechanism is quite simple at it's core: walk the filesystem, scanning every file matching a provided pattern, summing the file size and the unix mod time. When that sum changes it means one or more files were created, modified, or deleted and so, trigger some behavior. A much simpler rendition is found in [scantest](https://github.com/smartystreets/scantest), another tool I created for this purpose.

https://github.com/smartystreets/scantest/blob/master/main.go#L78-L106

The GoConvey behavior is more complex because it keeps track of which packages have been modified. An earlier version of scantest went even further, creating a dependency tree of the project and only run tests for modified packages and dependencies of modified packages (not every package in the project).

**Comment by ianwalter** [comment]
Thanks for your suggestions. I think my problems are related to VirtualBox shared folders and so I'm going to have to just run the server outside of Docker when developing for now.
