### ISSUE TITLE
Allow for short mode in go test

### ISSUE THREAD

**Issue by Thomasdezeeuw** [smartystreets/goconvey#338]
Go allows for `short` flag which only runs the fast tests and skips long running ones. Goconvey should allow for the same flag, which should simply passes it on to `go test`.

I'm willing to create if a pull request if it would be accepted.

**Comment by mdwhatcott** [comment]
This behavior is supported using profiles.

https://github.com/smartystreets/goconvey/wiki/Profiles

**Comment by Thomasdezeeuw** [comment]
Profiles seems very useful, however not every project I work is in my control. So I can't a profile to every project. Adding this option to the cli seems very useful to me. And if part of the code is already there it's seems very easy as well.

**Comment by mdwhatcott** [comment]
@Thomasdezeeuw:

There actually was a `-short` flag some time ago. But then we needed a `-parallel` flag, and then a `-run` flag, and you can probably see where that was headed as we considered duplicating all of the useful `go test` flags in the goconvey runner. Profiles was my solution to prevent that situation.

Can you think of another mechanism to provide the necessary flags in a way that doesn't require adding a `.goconvey` file in each package? Maybe the profiles could live elsewhere and be referenced by a new flag passed to the runner? I'm just thinking aloud at this point. Maybe there's an even more elegant solution waiting to be discovered...

**Comment by Thomasdezeeuw** [comment]
Maybe a single flag for all go test flags, something like this:

```bash
$ goconvey -timeout 1s
$ goconvey -timeout 1s -testflags -short -parallel 
```

Then `-short` and `-parralel` will be passed on to `go test`. Although I'm not sure how the default flag package reacts to this.

**Comment by mdwhatcott** [comment]
That doesn't feel very different from the original flag-passing solution. Again, I'd prefer not to pass flags wholesale from the goconvey runner to all packages being tested. The only exception I've made is the `-timeout` flag because of accidental infinite loops in code being tested causing the goconvey runner to hang indefinitely. Even that flag has caused some discord in the goconvey community. There's got to be a better, more pinpointed way...

**Comment by garpur** [comment]
I want to make a point in favor of passing the flags,

I am using "make" to run the tests and I want to be able to decide in the makefile which tests run eg:
  make tests-mock-only
  make-tests-db-only
which run the same tests but with different setup.

Using a config file does not solve this case since the file is the same for both targets.
