### ISSUE TITLE
WebUI: Refresh icon static instead of spinning

### ISSUE THREAD

**Issue by ruzz311** [smartystreets/goconvey#400]
After updating recently I noticed the refresh (aka re-run tests) button is no longer animated while the tests are running.

It seems like the javascript is applying/removing animating classes but I'm not sure they're correct.  It uses fa-spin-slow and I cannot find a class definition for it that involves animations.  Maybe updating font-awesome somewhere took that away?

![goconvey-ui-bug](https://cloud.githubusercontent.com/assets/419608/13503484/3d51c7ce-e135-11e5-8df9-b17b340ae827.gif)

I'd be glad to make the PR, just wanted to confirm someone else other than me saw it.

**Comment by mdwhatcott** [comment]
Yes, I've seen this too. Feel free to submit a fix.

**Comment by onlyjob** [comment]
Fonts-awesome was upgraded from 4.1 to 4.5. Here are issues fixed in fonts-awesome (changelog):
[4.5.0](https://github.com/FortAwesome/Font-Awesome/issues?q=milestone%3A4.5.0+is%3Aclosed)
[4.4.0](https://github.com/FortAwesome/Font-Awesome/issues?q=milestone%3A4.4.0+is%3Aclosed)
[4.3.0](https://github.com/FortAwesome/Font-Awesome/issues?q=milestone%3A4.3.0+is%3Aclosed)
[4.2.0](https://github.com/FortAwesome/Font-Awesome/issues?milestone=12&page=1&state=closed)

Can you spot anything relevant that might be responsible?

**Comment by onlyjob** [comment]
Maybe [this change](https://github.com/FortAwesome/Font-Awesome/commit/b3f34507b27b401834515f950383f1650398a3f1)...

**Comment by onlyjob** [comment]
I prefer to close bugs _after_ when fix is merged...

**Comment by ruzz311** [comment]
I don't remember closing it, and saw it close too - I just assumed it was some kind of hook since I referenced it in a PR.  I've reopened it.

**Comment by VorT3x** [comment]
Merged PR & verified.
